### ISSUE TITLE
Can't run "npm start" inside of the downloaded project

### ISSUE THREAD

**Issue by billy95008** [PacktPublishing/React-Design-Patterns-and-Best-Practices#1]
Hello,

I have a junior question. After downloaded all the code, I am not able to run it with "npm start". The error is not clear to me as this:

npm ERR! Failed at the react-design-patterns-and-best-practices@0.1.0 start scri
pt 'react-scripts start'.

node -v
v4.4.7
npm -v 
3.10.8

create-react-app has been installed. I am able to create new react app with create-react-app. But when running the 'npm start", I always got errors.

I do noticed that there is no node_modules directory in the downloaded src which it could be found on any testing app created by create-react-app.

**Comment by billy95008** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16325709/24481927/b4cb4400-14a2-11e7-8570-a3ad169d0849.png)

**Comment by techsachinkumar** [comment]
Hi billy95008,

Did you try installing all the node modules which are required?
Did you try npm install in the project folder ? 
Please try it and maybe that solves your issue.

Regards
